### ISSUE TITLE
resize picker show months bug

### ISSUE THREAD

**Issue by yuanjingxp** [xdan/periodpicker#14]
![image](https://cloud.githubusercontent.com/assets/13447106/14458195/246a1f78-00e2-11e6-94d3-a6a298a481bf.png)

resize the picker found the first column show the month is the same， my use in angularJS framework

**Comment by xdan** [comment]
Please update you plugin, this bug was fixed a long time ago

12.04.2016, 16:14, "长沙-怪侠" notifications@github.com:

> resize the picker found the first column show the month is the same， my use in angualrJS framework
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub

## 

C уважением,
Чупурнов Валерий
http://xdan.ru

**Comment by yuanjingxp** [comment]
This is the link to download my purchase yesterday of
can give me new download url?

**Comment by xdan** [comment]
Use this url http://xdsoft.net/jqplugins/periodpicker/?update#plugin_sender

12.04.2016, 15:17, "长沙-怪侠" notifications@github.com:

> This is the link to download my purchase yesterday of
> can give me new download url?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub

## 

C уважением,
Чупурнов Валерий
http://xdan.ru

**Comment by yuanjingxp** [comment]
thx!

**Comment by yuanjingxp** [comment]
confirm is fixed
