### ISSUE TITLE
Weird behaviour in demo (index.html)

### ISSUE THREAD

**Issue by FROGGS** [xdan/periodpicker#15]
Hi, when I open the index.html that is shipped, I get the following:

With firefox 45.0.1 (Ubuntu) and 38.0.1 (Windows)
Date is shown as "20 December 2012", but when I press F5, it turns into "1 December 2012".
When I press F5 again, it turns into "1 January 2012", and into "1 January 2001" after pressing F5 once more.

It does not happen using Internet Explorer.

Any clues?

**Comment by xdan** [comment]
This is ff behavior http://stackoverflow.com/questions/7377301/firefox-keeps-form-data-on-reload
I tryed do
that.startinput.attr('autocomplete', 'off'); in plugin
but firefox fills the field before

**Comment by FROGGS** [comment]
The autocompletion only was an issue because #16 existed...

Even if firefox now preserves the content of a field, it will be parsed correctly and therefore the date wont change. Closing as resolved with version 4.0.0.

Thank you!
