### ISSUE TITLE
Single day period, can't set start time

### ISSUE THREAD

**Issue by tvlahovi** [xdan/periodpicker#19]
Hello!
Thank you for making a great product and making it available for an affordable price.

I'm trying to display an inline periodpicker with a single day period, but it displays end time as starting time.
Demo here: ***

I tried to manually set the period time with something like this:

`jQuery('#z1').periodpicker('value', ['2010/03/12 21:00', '2010/03/12 22:00']);`

but in this case the period date will update, but time will not.
Multi day works fine.

Any suggestions?
Thanks!

**Comment by xdan** [comment]
Fixed in 4.0.5 Update please

**Comment by tvlahovi** [comment]
Works great.
Thank you!
