### ISSUE TITLE
Week selector does not select entire week across month boundary

### ISSUE THREAD

**Issue by jacogss** [xdan/periodpicker#20]
When selecting a week using the week selector button, only the days that are in the current month are selected. Example:

![pp](https://cloud.githubusercontent.com/assets/18721696/14888819/519cac82-0d5c-11e6-95b6-7727fd1df194.png)

**Comment by xdan** [comment]
And should it be otherwise ?

**Comment by benvdhgss** [comment]
Hi xdan,

I'm a colleague of jacogss. Yes, the behaviour we would expect is that all days belonging to a week get selected, even if that week has some days in one month and some in another.

 As the the screenshot above shows, if you click week 22 in may, it only selects 30 and 31st of May, and does not select the June 1 to 5, despite those belonging to week 22.

The use case for this is that we use the PeriodPicker to select a week range to download a report for that week. Another use case is that we often use it to select a specific week to view certain data.

A colleague of us has already bought the professional license, so it would be nice if this behaviour could change, in the way specified above.

Apart from the above, thank you for building this wonderful widget!

**Comment by xdan** [comment]
Oh, i'm sorry) I did not notice this. Fixed in 4.1.4. Please update
