### ISSUE TITLE
Events Documentation...

### ISSUE THREAD

**Issue by BallisticPain** [xdan/periodpicker#21]
So I dug into the source code and found that there are events... Yay!

Now we just need them documented with examples...
- [x] onAfterShow
- [x] onAfterHide
- [x] onAfterRegenerate
- [x] onOkButtonClick

Thanks for the great and affordable plugin!

**Comment by xdan** [comment]
Added http://xdsoft.net/jqplugins/periodpicker/#events

**Comment by BallisticPain** [comment]
Thanks a ton for the rapid addition to the documentation... I tried using onAfterHide with the below effects.

When I used onAfterHide I triggered another event... that was being triggered almost every time I did anything on the page and it would trigger a lot... which then caused a ton of Ajax requests to happen.

I'm going to use the onOkButtonClick as it's more what I want, but onAfterHide would work if they don't click the Ok button to close the modal.

**Comment by BallisticPain** [comment]
Just thought about it further... we update another PeriodPicker control on the page as part of the return of that Ajax call... we have to call `.periodpicker('change')` to make that show up in the control... is that also calling onAfterHide?
