### ISSUE TITLE
How can I disable the picker?

### ISSUE THREAD

**Issue by FROGGS** [xdan/periodpicker#22]
I've got a bootstrap modal where I show the picker control besides other elements.

In certain conditions I display the controls as readonly/disabled which means that the controls are drawn greyish and the cursor usually is `pointer: not-allowed`.

The periodpicker does not seem to allow that:

![periodpicker-disabled](https://cloud.githubusercontent.com/assets/141968/15244251/84250ad2-1900-11e6-9b18-0b9f87dae76e.png)

The picker still looks usable and in fact the picker shows up when I click on the control.

How can I make it look readonly/disabled and make the picker not show up on click?

**Comment by xdan** [comment]
Added enable, disable methods http://xdsoft.net/jqplugins/periodpicker/#disable

**Comment by FROGGS** [comment]
Works like a charm.

``` js
var $date = $modal.find('input[name="date"]');
$date.periodpicker(...);
$date.periodpicker('disable');
$modal.find('.period_picker_input').css('cursor', 'not-allowed');
```
