### ISSUE TITLE
hideAfterSelect ignored

### ISSUE THREAD

**Issue by ElmarKnipp** [xdan/periodpicker#23]
If I have a period picker like the below, after every click (e.g. after the selection of the start date), the calender is hidden. I have to click into the stopdate input field to select the end of the interval.

  jQuery('#startdate').periodpicker({
      end: '#stopdate',
      likeXDSoftDateTimePicker: true,
      hideAfterSelect: false
   });

**Comment by ElmarKnipp** [comment]
This error only appears in versions after period_picker.4.0.5.pro.

**Comment by xdan** [comment]
Fixed in 4.2.7 this bug because of hideOnBlur option.
 In your current version you can set 
http://xdsoft.net/jqplugins/periodpicker/#hideOnBlur in false
