### ISSUE TITLE
Setting a date interval doesn't work any more

### ISSUE THREAD

**Issue by ElmarKnipp** [xdan/periodpicker#24]
I bought period_picker.4.0.5.pro and setting a period with an array like in the example http://xdsoft.net/jqplugins/periodpicker/#value worked.

Since I updated the picker on 2016-05-12, I always get an JavaScript error "TypeError: e.isValid is not a function" when I use "jQuery('#z1').periodpicker('value', ['2010/03/12', '2010/03/18']);"

Something seems to be changed.

**Comment by xdan** [comment]
Fixed in 4.2.9
