### ISSUE TITLE
wrong directory in docu

### ISSUE THREAD

**Issue by ElmarKnipp** [xdan/periodpicker#25]
In the intro text "Getting Started" of http://xdsoft.net/jqplugins/periodpicker/ it is mentioned that you have to include 2 extra files, if you want to use the timepicker. The href of the css file is wrong.

It should point to the build directory:

<link rel="stylesheet" href="/build/jquery.timepicker.css">

and not

<link rel="stylesheet" href="/jquery.timepicker.css">

**Comment by xdan** [comment]
Thank you, fixed in documetation
