### ISSUE TITLE
DateTimePicker wrongly handles time part

### ISSUE THREAD

**Issue by ElmarKnipp** [xdan/periodpicker#26]
If you have the interval 24.12.2015 14:00 to 24.12.2015 15:00 the picker collapses to 24.12.2015 14:00 and looses the second time. It simply compares only the date and doesn't compare whether the time is also equal. The endtime is wrongly set to the starttime of 14:00 and not to 15:00.

<input type=text name=start id=start value="24.12.2015 14:00">
<input type=text name=stop id=stop value="24.12.2015 15:00">

   jQuery('#start').periodpicker({
      end: '#stop',
      cells: [1, 3],
      timepicker: true,
      formatDateTime:                   "DD.MM.YYYY HH:mm",
      formatDecoreDateTime:             "DD.MM.YYYY HH:mm",
      formatDecoreDateTimeWithoutMonth: "DD.MM.YYYY HH:mm",
      formatDecoreDateTimeWithYear:     "DD.MM.YYYY HH:mm",
      timepickerOptions: {
         hours: true,
         minutes: true,
         seconds: false,
         ampm: false,
         twelveHoursFormat: false,
         steps: [1, 5, 1, 1]
      }
   });

onsole.log ("value=" + jQuery("#start").periodpicker ('valueString'));

**Comment by xdan** [comment]
Fixed in 4.2.8
