### ISSUE TITLE
Fixed the onAfterHide Event

### ISSUE THREAD

**Issue by Sohryu7** [xdan/periodpicker#27]
Hi,

Bought your picker today, initially quite content, but after closer investigation having the same problems as this guy: https://github.com/xdan/periodpicker/issues/21 with the event.

Now I looked through the code and found this: 

```
if (!that.options.inline) {
 that.hide();
  if (that.options.likeXDSoftDateTimePicker && (that.startinput.is(e.target) || that.endinput.is(e.target))) {
     that.show(e.target);
   }
}                   
```

in Line 731 of jquery.periodpicker.js

you dont check if the picker is even opened, so the hide() event is called every time you click anywhere on the page. 

if you do it like this the event fires only once.

```
if (!that.options.inline) {
  if($('.period_picker_box').hasClass('visible')){
    that.hide();
  }
  if (that.options.likeXDSoftDateTimePicker && (that.startinput.is(e.target) ||   that.endinput.is(e.target))) {
    that.show(e.target);
  }
}
```

pretty sure theres a better way than checking for active class, but its a workaround.

---

Now to my actual quesion, is there a way to set the date with an ISOString? I'd like to use it like this: 
`jQuery('#periodpickerstart').periodpicker('value', (new Date("2016-05-18T08:30:00.000Z")))`

but getting the same err as this guy: https://github.com/xdan/periodpicker/issues/24

you wrote fixed in 4.2.6, but I only got the download link to 4.0.5oem, so where would I get the newest version?

**Comment by xdan** [comment]
http://xdsoft.net/jqplugins/periodpicker/?update#plugin_sender here, you may update
