### ISSUE TITLE
SASS files missing in download archive

### ISSUE THREAD

**Issue by sniechzial** [xdan/periodpicker#28]
The offered SASS files are not provided in the zip archive after purchasing the OEM license.

**Comment by xdan** [comment]
Hi, can you update your archive?
http://xdsoft.net/jqplugins/periodpicker/?update#plugin_sender

**Comment by sniechzial** [comment]
Hi,

unfortunately not ... I tried e-mail address and purchase code, Firefox and Chrome, the form just reloads, but nothing happens.

![image](https://cloud.githubusercontent.com/assets/1297938/15665831/b668b5be-270d-11e6-9321-f9affd59189a.png)

**Comment by xdan** [comment]
This script sends archive on your email. All OK?
