### ISSUE TITLE
same month

### ISSUE THREAD

**Issue by god8spiyo** [xdan/periodpicker#29]
![datepick2](https://cloud.githubusercontent.com/assets/11508644/15661384/22585f60-2711-11e6-941a-496668691b82.png)
![datepick](https://cloud.githubusercontent.com/assets/11508644/15661385/225bfd28-2711-11e6-8a2a-3219f7cf2bbe.png)

**Comment by xdan** [comment]
Fixed, already. Please update http://xdsoft.net/jqplugins/periodpicker/?update#plugin_sender

**Comment by god8spiyo** [comment]
ok thx !  one more .   I am click 2 time in one day But period same day next month ?

![datepick3](https://cloud.githubusercontent.com/assets/11508644/15666078/ee77c1c2-2738-11e6-9739-99e98bb7478b.png)

**Comment by god8spiyo** [comment]
![datepick4](https://cloud.githubusercontent.com/assets/11508644/15666106/0f3fac80-2739-11e6-8262-8ca54d91a94b.png)

**Comment by xdan** [comment]
@god8spiyo  Fixed?
