### ISSUE TITLE
Erroneous behavior when selecting the end time.

### ISSUE THREAD

**Issue by jdonzallaz** [xdan/periodpicker#3]
When you select the end time, behavior is unpredictable.
The picker always show the right datetime, but the input elements don't.

On first time change, end input take the right time. On the next change, start input take the choosen time.
![error_time](https://cloud.githubusercontent.com/assets/9055735/11417853/9a091aac-941a-11e5-954f-c313576b47d6.png)

Plus, when start and end dates are the same, you can choose an end time that is before the start time.
![error_time_same_day](https://cloud.githubusercontent.com/assets/9055735/11417895/fa59a2aa-941a-11e5-9101-78d5dee010a0.png)

**Comment by peter-gribanov** [comment]
For example see [this lebrary](http://www.daterangepicker.com/).
Library makes it impossible to select the end of the period less than the beginning of the period.

**Comment by xdan** [comment]
Fixed in 2.0.2
