### ISSUE TITLE
datetimepicker formatDecore is only applying format to FROM date vs FROM & TO dates

### ISSUE THREAD

**Issue by denisbetsi** [xdan/periodpicker#30]
Code:

```

PeriodPicker.prototype.getLabel = function () { 
...
                result.push(this.period[0].format(this.period[0].format('YYYY') !== this.period[1].format('YYYY') ? formats[0] : (this.period[0].format('M') !== this.period[1].format('M') ? formats[2] : formats[1])));
                result.push(this.period[1].format(formats[0]));
}

```

Only this.period[0] gets the special treatment, period[1] gets the default format.

**Comment by xdan** [comment]
It's right
`2001/01/12 - 2001/01/13`
label should be `12 - 13 January 2001` here `12` - periods[0] and   `13 January 2001` - is periods[1]
`2001/01/12 - 2001/02/13`
label should be `12 January  - 13 February 2001` here `12 January` - periods[0] and   `13 February 2001` - is periods[1]
`2001/01/12 - 2002/02/13`
label should be `12 January 2001  - 13 February 2002` here `12 January 2001` - periods[0] and   `13 February 2001` - is periods[1]

The second period will always have a full format

**Comment by denisbetsi** [comment]
Yeah only issue is, it's hard to tell which format to use in order to update these labels when it comes to range date format settings.
