### ISSUE TITLE
Troubles with AM/PM (solution inside)

### ISSUE THREAD

**Issue by polar-nik** [xdan/periodpicker#34]
When set `ampm: false` in `timepickerOptions`, time that we can scroll is still in range of 00:00 to 12:00.

On screen i'm highlight this issue.

![2016-06-22_15-51-36](https://cloud.githubusercontent.com/assets/12606182/16267275/91c5a0b0-3891-11e6-90a2-08a5bddbbd89.png)

**P.S.** Sry for my bad english ^^
### UPDATE (SOLUTION):

To fix it, we should also add option `twelveHoursFormat: false` to `timepickerOptions`

**Comment by xdan** [comment]
We should Picker's time format also changed , not only in timepickrs's
