### ISSUE TITLE
When programmatically setting date and time range, start time is 00:00

### ISSUE THREAD

**Issue by a-jackson** [xdan/periodpicker#35]
I've struggled to reproduce this outside of our application so I'm not sure what is triggering it,

however, it appeared it was setting the max time of start time to 00:00. I changed the following code in jquery.periodpicker.js

![image](https://cloud.githubusercontent.com/assets/2199309/16522352/40764bc8-3f95-11e6-9f0b-4a30dafd3938.png)

It seemed odd that it was checking the new time period was the same day but then setting the range to the previous values of the inputs.

This seems to have fixed the issue but I don't know what adverse effects it might have.

**Comment by BallisticPain** [comment]
This seems to be related to or is exactly what I was trying to describe here: https://github.com/xdan/periodpicker/issues/33#issuecomment-227298208
