### ISSUE TITLE
Cannot recreate after destroy

### ISSUE THREAD

**Issue by a-jackson** [xdan/periodpicker#36]
I cannot recreate the element after it has been destroyed. Looking at the code, the periodpicker function doesn't seem to handle the case of `opt` being the options to create a new one while `$this.data('periodpicker');` exists.

To fix this I added code to the destroy function to clear the periodpicker data from the element `this.startinput.data('periodpicker', null);`

Then, on recreate, a new PeriodPicker is created correctly.

**Comment by xdan** [comment]
Was fixed in 4.6.0
Please, update http://xdsoft.net/jqplugins/periodpicker/?update#plugin_sender

**Comment by a-jackson** [comment]
Using 4.7.3 this is still an issue

**Comment by xdan** [comment]
Sorry, fixed in 4.7.7
