### ISSUE TITLE
When picker is near the right, there is a horizontal scroll bar

### ISSUE THREAD

**Issue by a-jackson** [xdan/periodpicker#38]
When the page loads the picker popup is hidden but rendered near the picker. When the picker is near the right, this create a horizontal scroll bar on the page to allow space for the hidden popup.
Once the popup opens, it moves left to be on the screen and scroll bar disappears. 

The following produces an example

``` html
    <div style="width:100%">
        <div style="float:right;">
            <input type="text" id="periodpickerstart"/>
            <input type="text" id="periodpickerend"/>
        </div>
    </div>
```

**Comment by xdan** [comment]
I think you need solve this problem yourself
Picker can not take care of their environment
You can use regenerate event

**Comment by a-jackson** [comment]
The issue is that picker is being generated "off-screen" even though it is hidden.

I'd not suggesting that the picker change the environment, I'm saying that the picker should respect it's environment.

When you open the picker it checks the screen size and adjusts the position accordingly so it is not displayed off screen. The fix I have used is to use this code for setting the initial position as well so that  the picker is created on-screen in the first place.

I moved your code for calculating position on open into a function and then use on initialisation as well.

``` js
    PeriodPicker.prototype.getPosition = function (offset) {
        var top = offset.top + (!this.options.likeXDSoftDateTimePicker ? this.button.outerHeight() : $(target).outerHeight()) - 1;
        var left = offset.left;

        if (top + this.picker.outerHeight() > $(window).height() + $(window).scrollTop()) {
            top = offset.top - this.picker.outerHeight() - 1;
        }
        if (top < 0) {
            top = 0;
        }
        if (left + this.picker.outerWidth() > $(window).width()) {
            left = $(window).width() - this.picker.outerWidth();
        }

        return {
            left: left,
            top: top
        };
    }
```

**Comment by a-jackson** [comment]
Nice support...

**Comment by xdan** [comment]
Problem was solved long time ago, now picker hidden with display:none
