### ISSUE TITLE
should not be set empty when empty date is clicked

### ISSUE THREAD

**Issue by ben-nsng** [xdan/periodpicker#39]
The date (with class="period_picker_empty") is clicked, the date is reset. Any chance that the value should be kept and not change to empty?

![git-1](https://cloud.githubusercontent.com/assets/5063993/16844004/0e11a1c4-4a16-11e6-9d80-c6e9cf3de794.jpg)
![git-2](https://cloud.githubusercontent.com/assets/5063993/16844005/0e209134-4a16-11e6-89f5-80bfc08c42ec.jpg)

**Comment by xdan** [comment]
Fixed in 4.7.5
