### ISSUE TITLE
Wrong Year when  year changed

### ISSUE THREAD

**Issue by ghost** [xdan/periodpicker#40]
- select one date (lets say 27/07/2016);
- use the navigation arrow to try reach 31/01/2017.
- 2017 is never reached, as image shows.

![image](https://cloud.githubusercontent.com/assets/20689140/17188898/80eb8404-5415-11e6-963d-960b99176388.png)

**Comment by xdan** [comment]
Update please http://xdsoft.net/jqplugins/periodpicker/?update#plugin_sender

**Comment by ghost** [comment]
Is this a newer version, i bought and download this plugin 26/07/2016

**Comment by ghost** [comment]
Also, when i try to update using order id or email i get a message stating my email or invoice is invalid

**Comment by xdan** [comment]
Please write here you email

**Comment by ghost** [comment]
leonardo.barrea@adsolutions.com.br
