### ISSUE TITLE
Time Selection issue for Periodic Time

### ISSUE THREAD

**Issue by sg-satya** [xdan/periodpicker#41]
Hi,

I'm using a paid version plugin. But whenever I'm changing the date the time scroller become set as 12:00AM and can't the different time.

Please help!!

Thanks

**Comment by a-jackson** [comment]
Don't know if this will help you but, I had a similar issue when I first started with this where it would jump to 12:00AM and then not work. The issue turned out to be that I had not included jquery mousewheel correctly in my project.

**Comment by xdan** [comment]
You have included mousewheel?
