### ISSUE TITLE
How to get an event when user confirm a date by OK button

### ISSUE THREAD

**Issue by grzegorztomasiak** [xdan/periodpicker#44]
periodpicker has OK button which should trigger some event when user confirms the date, how can I get this right?

**Comment by grzegorztomasiak** [comment]
May I have an answer on that? It's stupid to pay for something and have a buggy software without minimal support

**Comment by xdan** [comment]
use options.onOkButtonClick works since 5.3.1

``` javascript
jQuery('#periodpickerstart')
    .periodpicker({
        onOkButtonClick: function () {
             if (this.period.length === 0) {
                    alert('please select period');
                    return false;
             }
        }
   })
```

**Comment by xdan** [comment]
You got to do this?
