### ISSUE TITLE
Selecting text in the time and date text input boxes in Internet Explorer

### ISSUE THREAD

**Issue by a-jackson** [xdan/periodpicker#47]
The text input boxes at the bottom of the popup can't be highlighted. In Chrome I can highlight and double/triple click to select but in IE this doesn't work.

Seems to be related to the CSS selector .xdsoft_noselect, .xdsoft_noselect \*

**Comment by a-jackson** [comment]
Changed to `.xdsoft_noselect,.xdsoft_noselect *:not(input)`

**Comment by xdan** [comment]
What IE version?

**Comment by a-jackson** [comment]
11

**Comment by xdan** [comment]
![image](https://cloud.githubusercontent.com/assets/794318/20177280/c683a3ce-a76d-11e6-82c6-26b257dc9136.png)
Work nice

**Comment by xdan** [comment]
Thank you, fixed in 5.3.6
