### ISSUE TITLE
Default Language Default Date Problem

### ISSUE THREAD

**Issue by oguzhansari** [xdan/periodpicker#51]
@xdan 
The default date does not depend on the selected language.
It gets better after clicking on it.

Default Date;
![periodpicker_datesave](https://cloud.githubusercontent.com/assets/13555457/21291559/d811400a-c4ec-11e6-8c55-614717142630.png)

After Click;
![periodpicker_datesave_2](https://cloud.githubusercontent.com/assets/13555457/21291560/d8127cb8-c4ec-11e6-95e1-b535e29977c7.png)

After Click;
![periodpicker_datesave_3](https://cloud.githubusercontent.com/assets/13555457/21291561/d8157422-c4ec-11e6-8831-e9e60b44491f.png)

**Comment by xdan** [comment]
Sorry, it was so long.
Latest fixed version here https://xdsoft.net/jqplugins/periodpicker/#plugin_sender
