### ISSUE TITLE
onClearButtonClick Event Documentation Needed

### ISSUE THREAD

**Issue by BallisticPain** [xdan/periodpicker#52]
@xdan Thanks for all your hard efforts with this plugin/project.

I now need an onClear event so I can be aware of the clear button being pressed. Namely in my case, I need it in order to trigger form validation.

Thoughts?
Jarvis

**Comment by BallisticPain** [comment]
So the event exists. However it should be documented... going to change the title of my issue to reflect this. Though there may need to be a code change to make the event like the others where it iterates over the methods and calls each of them.

Thanks!

**Comment by habworks** [comment]
Seems like they are few people posting or active on this repository.  Sorry to disturb you with this but can you comment on the other post **Error** on trigger any event. #60** if you have a fix.  Just looking for help.

**Comment by xdan** [comment]
Hi, thank you. Added
