### ISSUE TITLE
Return selected period as array, containing all days in the period.

### ISSUE THREAD

**Issue by Kristiansky** [xdan/periodpicker#53]
I want the periodpicker to return every day from the selected period, but currently it returns only start and end day. This is frustrating.
![image](https://cloud.githubusercontent.com/assets/11662094/22298883/c7629478-e32a-11e6-82bc-b8f444c23c45.png)
Can you guide me how to select every day and put it in the array?

**Comment by xdan** [comment]
For example all dates between two dates
```
var startDate = new Date();
var endDate = (new Date()).setFullYear(2019);

var dates = [];
while (startDate < endDate) {
dates.push(startDate.toString())
startDate.setDate(startDate.getDate() + 1)
}
console.log(dates)
```
