### ISSUE TITLE
24h support

### ISSUE THREAD

**Issue by hduchesn** [xdan/periodpicker#54]
Hi, is it possible to configure 24h instead of 12 AM/PM (24h is the most current usage over the world)
I have setted ampm:false but this just remove the field but doesn't switch hour to 24h

**Comment by dimir** [comment]
I agree. I have just bought the product, it's great, but I was surprised there is no way to completely get rid of 12-hour time format. I really need 24-hour format. Tried:

- twelveHoursFormat: false
- ampm: false

but still I get AM/PM in the opened dialog.

**Comment by hduchesn** [comment]
It works for me now, just forgot the tewelveHoursFormat:false... here is my config:

```
"timepicker": true,
"timepickerOptions": {
  hours: true,
  minutes: true,
  seconds: false,
  ampm: false,
  twelveHoursFormat:false
},
```

**Comment by dimir** [comment]
Ah, thanks a lot, it saved my day too! :-D

**Comment by FROGGS** [comment]
Please add twelveHoursFormat to the docs...
