### ISSUE TITLE
Arrow keys in the input field should not scroll the month or year pickers

### ISSUE THREAD

**Issue by ekangas1** [xdan/periodpicker#55]
When the focus is on the date or date/time input field, the presumption is that the user will be editing that using the keyboard (e.g. left/right arrow, deleted, entering numbers, etc.).  This keyboard should be restricted to the input field and should not causing the month picker to scroll.

E.g. click on the date input and press left-right arrow to move the cursor ... the expectation is that the year slider and day-of-month picker areas will not change.  Currently they scroll and the keyboard input is as a result kind of wonky.

Additionally, pressing "Enter" in the input field should trigger the "Ok" action.

I can manually add events to this and make this all happen as a layer over this tool, but it would be better if it was built-in.

**Comment by MarkSchultheiss** [comment]
I also observed this issue with 5.4.2 version

**Comment by xdan** [comment]
Thank you, fixed in 6.0.3
please download latest https://xdsoft.net/jqplugins/periodpicker/#plugin_sender
