### ISSUE TITLE
Request for "on pick date click ok" option

### ISSUE THREAD

**Issue by ekangas1** [xdan/periodpicker#56]
In the date and date-time pickers, it would be nice if we could have clicking on a date trigger the "Ok" event.  I have simulated this for date pickers (it doesn't work with time pickers due to clicking on times should not close it) using the following:

      $("#" + id).on("change", function() {
         // Skip when editing the inputbox...
         var f = $(".input_control:focus");
         if (f.length) return;

         jQuery('#' + id).periodpicker("hide");
         });

I.e. if the input field's content changes and we are not editing it with the keyboard, then close the dialog.

**Comment by BallisticPain** [comment]
@ekangas1 
I think what you're looking for is [hideAfterSelect](http://xdsoft.net/jqplugins/periodpicker/#hideAfterSelect)

**Comment by BallisticPain** [comment]
@ekangas1 Did the hideAfterSelect help? Or were you really wanting the Ok event to fire?
