### ISSUE TITLE
New Indication of Date Selected...

### ISSUE THREAD

**Issue by BallisticPain** [xdan/periodpicker#57]
We would like the ability to change the background color of the inputs once the start / end have been clicked. So when you click the first date the start control background goes green. I intend to solve the issue locally, but thought I should submit to you as an idea for a feature enhancement.

**Comment by BallisticPain** [comment]
So I think this would be the most flexibly done through emitting events...

```
fromSelected
toSelected

fromChanged
toChanged
```

I think you might also need a way to determine whether the developer wants to have the `toInput` auto receive the value. From the first selection.

**Comment by xdan** [comment]
Hi, thank you. Added in 6.0.2
https://xdsoft.net/jqplugins/periodpicker/#plugin_sender Download latest please
