### ISSUE TITLE
Period Picker for X Period

### ISSUE THREAD

**Issue by BallisticPain** [xdan/periodpicker#58]
I know there is `minDate` and `maxDate` for disabling days before and after... I haven't seen a way to specify the period that is allowed to even be moved through for the control? One of my requirements is `today + 1 year`. The primary issue is that if you end up scrolling too far one way or another it can be difficult to get back, whereas if there were less months / years to scroll through it would be simpler.

**Comment by BallisticPain** [comment]
@xdan Poke ... ;)

**Comment by BallisticPain** [comment]
@xdan Thoughts?

**Comment by xdan** [comment]
Hi, added in 6.0.1 if set maxDate when years pickers show only Years before that date, and some for minDate
