### ISSUE TITLE
problems with missing month

### ISSUE THREAD

**Issue by psyafter** [xdan/periodpicker#6]
there are many situations when month is missing.

fix it by:
in every place where you are manipulating date< you should reorder commands. first command is setDate, then setYear, then setMonth (always last).

for example:

was:
        date.setFullYear(this.year);
        date.setMonth(this.month - 1);
        date.setDate(1);

change to:
        date.setDate(1);
        date.setFullYear(this.year);
        date.setMonth(this.month - 1);

there 3-4 places when you should to change it

in function TimeWrapper, that.clone = function  **add** before tmp.setFullYear
tmp.setDate(1);

**Comment by xdan** [comment]
It is used for scroll moths. 

```
that.picker.on('mousewheel', function (e) {
                that.month += (that.options.reverseMouseWheel ? -1 : 1) * e.deltaY;
                that.regenerate();
                return false;
 });
```

 that.month can be more than 12 (25, 100, 1000)
