### ISSUE TITLE
Error on trigger any event.

### ISSUE THREAD

**Issue by felipesmendes** [xdan/periodpicker#60]
Hi,

I'm trying to do this with the okbutton 

 ```
onTodayButtonClick: function () {
                this.day = moment.date();
                this.month = moment.month();
                this.year = moment.year();
                this.regenerate();
                return false;
            },
onOkButtonClick: function () {
                console.log(this);
            }
```

and got this error:

> jquery.periodpicker.js:413 Uncaught ReferenceError: that is not defined
>     at PeriodPicker.__safecall (jquery.periodpicker.js:413)
>     at HTMLButtonElement.<anonymous> (jquery.periodpicker.js:777)
>     at HTMLDivElement.dispatch (jquery.js:3)
>     at HTMLDivElement.r.handle (jquery.js:3)

Have any fix for that?

**Comment by habworks** [comment]
Greetings - did you ever find a fix for this?  If so, can you please reply what that fix was.

**Comment by xdan** [comment]
Hi guys, sorry, i fied this issue only now. Please download latest version here https://xdsoft.net/jqplugins/periodpicker/#plugin_sender

**Comment by felipesmendes** [comment]
Error displaying the error page

*Att,*

*Felipe Silveira Mendes*Twitter <https://twitter.com/felipesmendes> -
Linked-In <http://www.linkedin.com/pub/felipe-silveira/33/247/496>
*Web Developer*
*(31) 8370-9090 (Claro)*
*contato@felipems.com.br <contato@felipems.com.br>*



2017-11-25 22:00 GMT-02:00 Valeriy <notifications@github.com>:
