### ISSUE TITLE
How to make Time picker to show in right Side in periodpicker

### ISSUE THREAD

**Issue by vikasinnoeye** [xdan/periodpicker#64]
Hello,

It there any way to show the time picker to right side of date picker instead of left side in periodpicker.

I am using following Script:

<script type="text/javascript">
jQuery('#periodpickerstart').periodpicker({

timepicker: true, // use timepicker
  timepickerOptions: {
    hours: true,
    minutes: true,
    seconds: false,
    ampm: true
  },

  norange: true, // use only one value
  cells: [1, 1], // show only one month

  resizeButton: false, // deny resize picker
  fullsizeButton: false,
  fullsizeOnDblClick: false,
});
</script>

Any help is appreciated. Thanks
![untitled](https://user-images.githubusercontent.com/30344944/33313416-973a8cfc-d450-11e7-818a-3a0b2319067e.png)

**Comment by xdan** [comment]
Hi, added in 5.9.9 https://xdsoft.net/jqplugins/periodpicker/#timePickerInRight
Please update https://xdsoft.net/jqplugins/periodpicker/?update#plugin_sender
