### ISSUE TITLE
maxDate

### ISSUE THREAD

**Issue by RoIVIan-V** [xdan/periodpicker#65]
При наличии параметра maxDate в настройках и cells больше одного месяца, лучше бы последним месяцем ставить как раз тот, на который указывает maxDate. Так будет логичнее и удобнее.

**Comment by xdan** [comment]
Здравствуйте. Спасибо, добавил в 5.9.8
Обновите пожалуйста. https://xdsoft.net/jqplugins/periodpicker/?update#plugin_sender
