### ISSUE TITLE
no js file in source

### ISSUE THREAD

**Issue by chayodom** [xdan/periodpicker#66]
Not found  build/jquery.periodpicker.full.with.tp.min.js
from download payment source

**Comment by xdan** [comment]
Hi, it is bug in index.html. Fixed. 
build/jquery.periodpicker.full.with.tp.min.js  - real name build/jquery.periodpicker.full.min.js
Please download latest version.
https://xdsoft.net/jqplugins/periodpicker/?update#plugin_sender
