### ISSUE TITLE
Periodpicker with time picker input time

### ISSUE THREAD

**Issue by Yves-K** [xdan/periodpicker#67]
Hello,
Using periodpicker with timepicker : true
When input has a time value it is not set on the picker (date is !)

Regards

**Comment by xdan** [comment]
```
<input type="text" id="picker" value="8:00"/>
```
```
$('#picker').periodpicker({
timepicker: true
});
```
so?

**Comment by Yves-K** [comment]
Hello thank you for your answer

BUT

I'm setting the date/time value after initialization (trigerring a 'dataSet') and

```
field.on('dataSet', function(event){
	$(this).periodpicker('change'); 
});	
```

Date is changed, not time !!!

Best reagards

**Comment by xdan** [comment]
Hi, in 6.2.3 added 
```
input.value = '08:12';
$(input).periodpicker();
input.value = '09:42';
$(input).periodpicker('change');
```

**Comment by kclark6595** [comment]
Having the same issue.  Just purchased and downloaded yesterday, but link is for version 6.1.8.  How do I get the 6.2.3 version??

**Comment by xdan** [comment]
https://xdsoft.net/jqplugins/periodpicker/ click `I have already bought the product. How to updade?`

**Comment by xdan** [comment]
Or https://xdsoft.net/jqplugins/periodpicker/?update#plugin_sender

**Comment by IndyDevGuy** [comment]
Yea that isnt working for me, I bought the OEM license and tried my email and my order number.
