### ISSUE TITLE
Update disableDays option

### ISSUE THREAD

**Issue by pgnjidic** [xdan/periodpicker#68]
Hello,

Is it possible to change and update the disableDays option anyway?  I didn't see the possibility.

Thanks,
Petar

**Comment by xdan** [comment]
You can change any options  https://xdsoft.net/jqplugins/periodpicker/#setOption

**Comment by pgnjidic** [comment]
I tried but when I disable days after that it's impossible to re-enable them again

**Comment by xdan** [comment]
You should have called the `regenerate` method after `setOption`, but in 6.2.4 made it to be called automatically
