### ISSUE TITLE
missing calendar day when last day of month is first day of week

### ISSUE THREAD

**Issue by psyafter** [xdan/periodpicker#7]
fix:
in PeriodPicker.prototype.generateCalendarLine
...
while (j < countDaysInMonth && ticker < 100) {

change to:
while (j <= countDaysInMonth && ticker < 100) {

**Comment by xdan** [comment]
You need update your plug-in. This error has been fixed for so long

**Comment by psyafter** [comment]
I sent you email (reply on mail with license) and asked you to send me new version but I has not received anything..

**Comment by xdan** [comment]
You can download the update yourself http://xdsoft.net/jqplugins/periodpicker/?update

**Comment by psyafter** [comment]
fine, thank you.
