### ISSUE TITLE
Problem with setOption / setOptions

### ISSUE THREAD

**Issue by bartekb** [xdan/periodpicker#72]
I noticed that setOption does not work for me. When I try:

`$('.completion--date').periodpicker('setOptions',{'minDate' : '2018-03-01'});`

or 

`$('.completion--date').periodpicker('setOptions',{'lang' : 'ru'});`

Nothing happens. Moreover, when I try this:

`$('.completion--date').periodpicker('setOption', 'lang', 'ru');`

an error shows up:

`Uncaught TypeError: Cannot set property 'lang' of undefined.` 

I'm using single datepicker with timepicker enabled without any events defined:

```
$('.completion--date').periodpicker({
        norange: true,
        cells: [1, 1],
        resizeButton: false,
        animation: false,
        fullsizeButton: false,
        fullsizeOnDblClick: false,
        timepicker: true,
        formatDate: 'YYYY-MM-DD',
        formatDateTime: 'YYYY-MM-DD H:i',
        formatDecoreDateTimeWithYear: 'YYYY-MM-DD HH:mm',
        timepickerOptions: {
          hours: true,
          minutes: true,
          seconds: false,
          ampm: false,
          twelveHoursFormat: false
        }
      });
```

**Comment by bartekb** [comment]
@xdan I'm using 6.1.8. This is most likely the cause. I received such a version in the e-mail with the order. Unfortunately, I can not download the new version because this message appears after two hours of purchase:

> Error! Your order is not found . If you just bought a product then please wait for some time.

**Comment by xdan** [comment]
You got the latest version? Try download the latest version now https://xdsoft.net/jqplugins/periodpicker/?update#plugin_sender
