### ISSUE TITLE
Error on inputs

### ISSUE THREAD

**Issue by dferreiraLux** [xdan/periodpicker#8]
On latest version (2.6.6), when you select time, it's not reflected on the Input in the page.
It's always at "00:00" (or at the default time used, here : "23;45").

![image](https://cloud.githubusercontent.com/assets/17121649/12883867/e203cd82-ce5a-11e5-9ee9-41ffd5c9b842.png)

![image](https://cloud.githubusercontent.com/assets/17121649/12883939/4ec27248-ce5b-11e5-8ca9-ba8b4eb15cf9.png)

**Comment by xdan** [comment]
Thank you. Fixed in 2.7.7

**Comment by dferreiraLux** [comment]
Thank you; perfect and quick response.
