### ISSUE TITLE
The period picker loop on the same year

### ISSUE THREAD

**Issue by panthony** [xdan/periodpicker#9]
When I tried to select a period from December to January of the following year I noticed that the months where looping on the same year:

![screen shot 2016-02-23 at 09 00 49](https://cloud.githubusercontent.com/assets/230462/13245240/2c1083b8-da0c-11e5-80e8-1327f029d935.png)

In this case we would expect January 2018 instead of January 2017.

Because of this it is very counter intuitive to select a period across two years.

I have to first pick a date in December, click on the next year in the 'period' select on top (meaning I can't hide it) then select the second date in January.

If there is an option to choose the behavior I could not find it.

If there is none is it possible to address this issue ? I'd like to purchase the period picker but I can't because of this.

**Comment by edislasm** [comment]
I also found this and vote on it to be fixed soon!

**Comment by xdan** [comment]
Thank you, fixed. Please download latset version here http://xdsoft.net/jqplugins/periodpicker/?update#plugin_sender
